#include "includes/variables.h"

const int outputPins[MAX_CONFIGURABLE_PLUGS] = {
    CONFIG_SWITCH_1_OUTPUT_PIN, 
    CONFIG_SWITCH_2_OUTPUT_PIN,
    CONFIG_SWITCH_3_OUTPUT_PIN,
    CONFIG_SWITCH_4_OUTPUT_PIN,
    CONFIG_SWITCH_5_OUTPUT_PIN,
    CONFIG_SWITCH_6_OUTPUT_PIN,
    CONFIG_SWITCH_7_OUTPUT_PIN,
    CONFIG_SWITCH_8_OUTPUT_PIN,
};
const int inputPins[MAX_CONFIGURABLE_PLUGS] = {
    CONFIG_SWITCH_1_INPUT_PIN,
    CONFIG_SWITCH_2_INPUT_PIN,
    CONFIG_SWITCH_3_INPUT_PIN,
    CONFIG_SWITCH_4_INPUT_PIN,
    CONFIG_SWITCH_5_INPUT_PIN,
    CONFIG_SWITCH_6_INPUT_PIN,
    CONFIG_SWITCH_7_INPUT_PIN,
    CONFIG_SWITCH_8_INPUT_PIN,
};
